import test from 'node:test';
import assert from 'node:assert/strict';
import { registerAccount, loginAccount, currentAccount, readAccount, saveAccount, changePassword, logoutAccount, deleteAccount } from '../src/features/auth/data/localAccount.js';
const storage = () => { const data = new Map(); return { getItem: key => data.get(key) ?? null, setItem: (key, value) => data.set(key, value), removeItem: key => data.delete(key) }; };
test('local profile checks credentials, persists edits and supports logout and deletion', async () => {
  globalThis.localStorage = storage(); globalThis.sessionStorage = storage();
  await registerAccount({ name: 'Test', surname: 'User', email: 'test@example.com', tel: '501234567', date: '2000-01-01', password: 'sample-password' });
  assert.equal(currentAccount(), null);
  assert.equal(readAccount().password, undefined);
  await assert.rejects(loginAccount('test@example.com', 'wrong'));
  await loginAccount('TEST@example.com', 'sample-password');
  saveAccount({ fullName: 'Updated Name' });
  assert.equal(currentAccount().fullName, 'Updated Name');
  await assert.rejects(changePassword('wrong', 'replacement-password'));
  await changePassword('sample-password', 'replacement-password');
  logoutAccount(); assert.equal(currentAccount(), null);
  await assert.rejects(loginAccount('test@example.com', 'sample-password'));
  await loginAccount('test@example.com', 'replacement-password');
  deleteAccount(); assert.equal(readAccount(), null); assert.equal(currentAccount(), null);
});
